name: Postman API Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Install Newman CLI
      - name: Install Newman
        run: npm install -g newman

      # 3️⃣ Install Newman Allure Reporter
      - name: Install Newman Allure Reporter
        run: npm install -g newman-reporter-allure

      # 4️⃣ Install Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline

      # 5️⃣ Run Postman Collection with Allure
      - name: Run Petstore API Collection
        run: |
          newman run "Petstore API Automation.postman_collection.json" \
            -r allure \
            --reporter-allure-export allure-results

      # 6️⃣ Generate Allure Report
      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      # 7️⃣ Upload Allure Report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Report
          path: allure-report
